version: '2.1'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 85:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
      # - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - APPLICATION_URL=http://ec2-3-83-112-152.compute-1.amazonaws.com
    links:
      - backend

  backend:
    container_name: backend
    image: backend
    build: .
    restart: always
    expose:
      - "3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
