version: '2.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DHPARAM_GENERATION: "false"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


  backend:
    image: backend
    build: .
    environment:
      VIRTUAL_HOST: ec2-3-83-112-152.compute-1.amazonaws.com
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

